stages:
- name: Codeception test
  steps:
  - runScriptConfig:
      image: php:7.2
      shellScript: |-
        apt-get update
        apt-get install -y --no-install-recommends git zip libsqlite3-dev zlib1g-dev
        docker-php-ext-install zip
        curl --silent --show-error https://getcomposer.org/installer | php
        ./composer.phar install -n --prefer-dist
        touch storage/testing.sqlite storage/database.sqlite
        cp .env.testing .env
        php artisan migrate
        php artisan migrate --env=testing --database=sqlite_testing --force
        ./vendor/bin/codecept build
        ./vendor/bin/codecept run
- name: Publish image php-fpm
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: ./7.2-fpm
      tag: php-fpm:${CICD_EXECUTION_SEQUENCE}
- name: Publish image nginx
  steps: 
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: ./nginx
      tag: nginx:${CICD_EXECUTION_SEQUENCE}
- name: Publish image varnish
  steps: 
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: ./varnish
      tag: varnish:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
